apiVersion: v2
name: osac
description: Open Sovereign AI Cloud
type: application
version: 0.0.1

dependencies:
  - name: osac-operator-crds
    version: ">=0.0.0"
    repository: "file://../../base/osac-operator/charts/operator-crds"
    alias: operatorCrds
  - name: osac-operator
    version: ">=0.0.0"
    repository: "file://../../base/osac-operator/charts/operator"
    alias: operator
  - name: fulfillment-service
    version: ">=0.0.0"
    repository: "file://../../base/osac-fulfillment-service/charts/service"
    alias: service
  - name: osac-aap
    version: ">=0.0.0"
    repository: "file://../../base/osac-aap/charts/aap"
    alias: aap
