{{- if .Values.dbMigrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osac.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "osac.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: {{ .Values.dbMigrate.image }}
        command:
        - fulfillment-service
        - migrate
        {{- if .Values.dbMigrate.dbUrl }}
        - --db-url
        - {{ .Values.dbMigrate.dbUrl | quote }}
        {{- end }}
        {{- if .Values.dbMigrate.dbUrlFile }}
        - --db-url-file
        - {{ .Values.dbMigrate.dbUrlFile | quote }}
        {{- end }}
  backoffLimit: 3
{{- end }}
