apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: osac

resources:
  - ../../base
  - externalsecrets

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: osac-operator-controller-manager
        namespace: osac-operator-system
      spec:
        template:
          spec:
            containers:
            - name: manager
              env:
              - name: OSAC_AAP_TEMPLATE_PREFIX
                value: osac
              - name: OSAC_AAP_URL
                value: "https://osac-aap-osac.apps.hypershift2.nerc.mghpcc.org/api/controller"
              - name: OSAC_AAP_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: osac-aap-api-token
                    key: token
                    optional: true
              - name: OSAC_AAP_INSECURE_SKIP_VERIFY
                value: "true"
              - name: OSAC_AAP_STATUS_POLL_INTERVAL
                value: "30s"
              - name: OSAC_FULFILLMENT_SERVER_ADDRESS
                value: fulfillment-internal-api:8001

secretGenerator:
  - name: config-as-code-ig
    options:
      disableNameSuffixHash: true
    literals:
      - AAP_EE_IMAGE=ghcr.io/osac-project/osac-aap:latest

configMapGenerator:
  - name: publish-templates-ig
    options:
      disableNameSuffixHash: true
    literals:
      - OSAC_TEMPLATE_COLLECTIONS=osac.templates,isaiahstapleton.ai_cluster_ansible
      - OSAC_FULFILLMENT_SERVICE_URI=https://fulfillment-internal-api:8001

replacements:
- path: console-proxy-replacements.yaml

images:
  - name: ghcr.io/osac-project/osac-operator
    digest: sha256:9b271b405219e6be4c61259b8ebfcb3b41a7fa58ecccd6ada93c10d046f510a8
  - name: ghcr.io/osac-project/fulfillment-service
    newTag: v0.0.30
  - name: ghcr.io/osac-project/fulfillment-controller
    newTag: v0.0.30
